"""Add speaker notes to MedQuAD_Robustness_Final_Presentation_n50_polished.pptx.

Reads:  MedQuAD_Robustness_Final_Presentation_n50_polished.pptx
Writes: MedQuAD_Robustness_Final_Presentation_n50_polished_with_notes.pptx

Notes are presenter-first ("what you'd actually say"), targeted to a 15–20 min
academic final with ~3 min Q&A buffer. Each slide ends with a transition cue.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from pptx import Presentation

REPO = Path(__file__).resolve().parents[2]

# Look for the polished file under either of its known names. The user may
# rename the polished output (we've seen `_v2.pptx`); fall back gracefully.
_CANDIDATE_NAMES = (
    "MedQuAD_Robustness_Final_Presentation_v2.pptx",
    "MedQuAD_Robustness_Final_Presentation_n50_polished.pptx",
)
SRC = next((REPO / n for n in _CANDIDATE_NAMES if (REPO / n).exists()), REPO / _CANDIDATE_NAMES[0])
DST = SRC.with_name(SRC.stem + "_with_notes" + SRC.suffix)

NOTES: dict[int, str] = {
    1: """Hi, we're Group 2 — Medical LLM Robustness.

We tested whether a prompt-repair step actually helps medical QA models answer messy real-user questions, or whether it just looks like it helps.

This is the n=50 pilot: 11 answer models, 5 noise types, two repair pipelines (fixed_repair and self_repair). About 16 minutes of content.

→ Move to the problem.""",

    2: """The motivation is simple. Real users don't ask clean benchmark questions.

MedQuAD is curated NIH/NLM content — careful, well-formed phrasing. Patients in the wild type at midnight: typos, vague wording, missing context, layperson terms.

In healthcare that isn't just a UX problem. Vague phrasing changes which medical concepts a model retrieves, which risks it surfaces, and how confident the user feels in the response.

So our research question: **Can a prompt-repair step recover the answer quality lost under noisy user input?**

The numbers up top: 11 models, 50 questions per model, 5 noise types — that's the scale we're working with.

→ Before methodology, let's make sure we share vocabulary.""",

    3: """One-sentence version: we take real medical questions, make them messy like real-user input, try to repair them, then check whether the LLM answer gets better or worse.

The flow at the top is the pipeline: clean question → noisy version → repaired version → model answer → score vs reference.

Four terms to keep in mind:
• **Noise** — a controlled way of making the question harder (typo, vague phrasing, missing detail, layperson wording, overgeneralization).
• **Repair** — a rewrite step that tries to make the messy question clearer WITHOUT answering it.
• **Robustness** — does the model still answer well when input is messy?
• **Recovery** — does repair pull the answer back toward what we'd get on the clean question?

These four words cover everything in the rest of the talk.

→ With shared vocabulary, here's the actual experimental design.""",

    4: """Three pipelines per question:
• Clean → answer model → clean answer (our baseline).
• Noisy → answer model → noisy answer (the degradation).
• Noisy → repair → answer model → repaired answer (the recovery test).

We ran this structure in two modes, on purpose, because they answer different questions.

**fixed_repair**: GPT-5.4 generates ONE shared noisy set and ONE shared repaired set. All 11 models see identical inputs. Best for fairness — every model is judged on the same prompts.

**self_repair**: all models see the same noisy questions, but each model repairs its own. That's closer to a deployed system where the answer model also handles repair.

The two modes give us a controlled comparison and a realistic comparison.

→ Here's exactly what was tested.""",

    5: """The scale: 11 answer models × 50 questions × 5 noise types = 550 rows per mode, evenly distributed by round-robin so every model sees 10 examples of each noise type.

Models span four families:
• Closed API: GPT-5.4.
• Open-weight instruction-tuned: Llama 3.1, Mistral 7B, Mixtral 8x7B, Qwen2.5 14B/32B, Qwen3 32B, Gemma 2 9B, Gemma 4 31B, Phi-3 med.
• Medical-domain: BioMistral-7B.
• Quantized local variants — 4-bit and Q6_K — to test whether quantization changes robustness behavior.

Noise types simulate the five most common failure modes we see in real user questions: typos and grammar slips, ambiguity, layperson rewording, incomplete prompts, and overgeneralization. Noise itself is generated by GPT-5.4-mini using fixed templates.

→ How we evaluate is its own slide.""",

    6: """We use 11 metrics across 5 families. No single metric captures medical QA robustness, so we layer them.

• **Lexical overlap** — BLEU, chrF, ROUGE-L, Token F1, Exact Match. Each tolerant of different surface variations. Exact Match is mostly zero for free-form QA, included for completeness.
• **Semantic answer** — BERTScore. Catches paraphrase that lexical metrics miss.
• **Question intent** — embedding similarity between the clean question and the noisy/repaired version. Tells us whether the user's actual ask was preserved.
• **Judge score** — G-Eval, where GPT-5.4-mini scores 1–5 on answer quality given question, reference, and answer.
• **Medical content** — coverage, precision, and F1 of medical terms vs the reference, using a MedQuAD-derived lexicon.

Don't memorize all of them — the next slide tells you which ones to actually watch.

→ One reading rule before results.""",

    7: """This slide is the most important interpretation rule in the talk.

**Repair can clean up the question while still hurting the answer.**

Intent metrics will improve almost by definition — repair's job is to clarify the user's ask, so similarity to the clean question goes up.

But a cleaner question doesn't guarantee a better answer. The model can still drop medical content, drift to a different topic, or lose specificity. We'll see all three failure modes in the evidence examples.

So we never rely on one metric. We pair intent with answer quality (G-Eval) and medical content (med_coverage / med_f1). When those agree, the story is clean. When they diverge, that divergence IS the story.

→ With that said — here's the headline.""",

    8: """The headline of the n=50 pilot: repair did not systematically improve answer quality.

Walk through the numbers: clean G-Eval averages 3.73. Noise drops it to 3.47. Repair pulls it back to **3.35 in fixed_repair** and **3.41 in self_repair** — both BELOW the noisy baseline.

Read that twice. On average, repair did NOT recover what noise took away. In fixed_repair it actually made things slightly worse on average.

(Pause for a beat — this is the counterintuitive moment.)

Important caveat: averages mask variance. Some models recovered strongly. Some got much worse. We'll show that distribution next.

And: this finding is the OPPOSITE of what intent metrics show — those improved everywhere. That gap between intent and answer quality is the actual finding.

→ Let's open up the average per model.""",

    9: """Bars show repaired-minus-noisy G-Eval — positive means repair helped, negative means repair hurt. Top of the chart sorted to put the biggest self_repair winners first.

Two clear positive outliers in self_repair:
• **Qwen3 32B at +1.32** — biggest gain in the study.
• **Mixtral 8x7B at +0.66**.

Both of these models can rewrite their own bad input usefully. Their fixed_repair gain is much smaller, which suggests it's the SELF-rewriting capability that helps, not just having a cleaner prompt.

Most other models — Phi-3 med, Gemma 4 31B, Mistral 7B, Qwen2.5, Llama, GPT-5.4 — are flat or worse after repair. Several lose 0.3 to 0.6 G-Eval points.

Fixed-repair (the controlled mode) is even more conservative: only Qwen3 and BioMistral marginally improve.

Takeaway: **repair effectiveness is model-specific.** It is not a free lunch you can apply across the board.

→ It's also not just about model — noise type matters.""",

    10: """Same delta — repaired minus noisy — broken down by noise type instead of by model.

Self-repair helps slightly on **typos/grammar** and **incomplete** questions. These are surface-level issues; once the question is cleaned up, the model can answer.

Layperson phrasing and overgeneralization stay difficult — repair often locks in the wrong framing or broadens too far. We'll see exactly that in slide 13.

Practical implication: repair should be CONDITIONAL. Apply it to typos and incomplete prompts; don't apply it blindly to ambiguous or overgeneralized prompts where it might commit to the wrong interpretation.

→ And here's the deeper pattern across the full metric stack.""",

    11: """This table is the core finding compressed into one view.

For each metric we count, across the 11 models: how many improved, how many got worse, how many stayed flat after repair.

The standout row is at the bottom: **Intent preservation — 11 / 0 / 0** in BOTH modes. Every single model's repaired question was closer to the clean question than its noisy version. Repair, in that narrow sense, always works.

Now look at every other row:
• G-Eval: 2 improved / 8 worse in fixed mode. 2/9 in self mode.
• BERTScore: 2/9 / 3/8.
• **med_coverage in self_repair: 0/11/0.** Every single model lost medical-term coverage.
• med_f1: 4/7 in fixed, 1/10 in self.

**Core pattern**: repair makes the question better, but not the answer. If we had only reported intent, we'd be telling a misleadingly positive story.

→ Now let me show concrete examples of what's actually happening.""",

    12: """GPT-5.4, incomplete-noise question.

Clean question: "Do you have information about Air Pollution." Noisy: "do u have any info on bad air stuff and what it can do."

Look at the noisy answer: literal one-line fragment. "Yes — bad air." G-Eval crashes from 4 to 1. med_coverage from 27 to 2.

Repair turns the question into "What health effects can poor air quality or air pollution have on the body" — a clean medical ask. The answer comes back: irritation, asthma, COPD, lung function. G-Eval back to 4. med_coverage recovers to 16.7.

**This is repair working as designed.** Most of the lost medical content came back. This is the kind of case that makes you think repair is a safety layer.

→ But it doesn't always work this cleanly.""",

    13: """Same model, same noise type, different question — and the failure mode shows up.

Clean topic: "Anabolic Steroids." Noisy: "those muscle-building stuff." Repair rewrites it as "health risks of muscle-building supplements OR anabolic steroids."

**Notice what just happened.** Repair widened the question. The original clean topic was anabolic steroids specifically — a regulated, prescription-context medical concept. The repaired version now ALSO includes generic supplements like protein powder.

The answer drifts. The repaired answer talks mostly about protein powder, creatine, pre-workouts. The medical concept shifted before the answer model ever saw the question.

G-Eval is 3 — slightly better than the noisy 2 — but med_coverage went 28 → 7 → 13. We never recover the original medical specificity.

**This is the central failure mode**: question repair commits to the wrong interpretation. The answer model is now answering a different question.

→ Layperson noise has the same trap.""",

    14: """Layperson noise. The clean question is just "What is abortion." The noisy version is a long patient-language paraphrase: "what does it mean when a pregnancy gets ended early or the baby is not kept…"

Repair handles this well. It restores a concise medical distinction: spontaneous abortion (miscarriage) versus induced abortion. The answer comes back tight and clinically accurate. G-Eval recovers to 4. med_coverage holds at 23.

The takeaway here is the contrast with the previous slide: layperson noise CAN be repaired well, but only when repair correctly identifies the medical category. When the layperson framing is ambiguous, repair has to guess — and sometimes guesses wrong.

→ One more example, showing why we don't trust G-Eval alone.""",

    15: """Mixtral 8x7B, typos-noise question on anal disorders. The judge G-Eval scored the repaired answer **5 — a perfect score**.

But look at med_coverage: **22.2 → 19.4 → 16.7**. Coverage falls steadily through both noise AND repair, even as G-Eval improves.

The repaired answer reads as fluent and well-organized, which is what GPT-5.4-mini judges on. But the medical content audit sees fewer specific terms — fewer named conditions, less precision.

**This is exactly why we layer metrics.** A judge alone would tell us the system improved. The medical lens says we lost specificity. Both are true. Whether that matters clinically depends on what's missing.

→ So what does all this evidence add up to?""",

    16: """Three things from the n=50 evidence.

**One: repair is useful but bounded.** It can fix surface noise — typos, missing words, layperson terms. It cannot reliably recover medical meaning once the prompt has actually drifted in topic.

**Two: question repair adds another failure mode.** The repair model can commit to the wrong interpretation, broaden the target, or shift the medical category — all BEFORE the answer model ever sees the question. Slide 13 was the textbook case.

**Three: metric choice changes the story.** Intent metrics improve across the board. Judge scores sometimes improve. Medical content quietly falls. Multi-lens evaluation isn't optional in this domain.

If you want a one-line answer to the research question: **prompt repair is a conditional tool, not a safety layer.**

→ We're being deliberately conservative about what this pilot can claim.""",

    17: """What this pilot CANNOT yet claim, on purpose.

• **Pilot scale.** 50 questions per model is enough for signal-finding, not for confidence intervals on per-model effects.
• **Synthetic noise.** GPT-generated noise is consistent and controlled. Real patient language is messier, multimodal, and includes things like image attachments and EHR context.
• **Single dataset.** MedQuAD is curated NIH/NLM content. Patient portal messages, telehealth chats, and EHR notes look different and would likely show different repair behavior.
• **Judge model overlap.** G-Eval uses GPT-5.4-mini; our repair/noise stack also uses GPT-family components. Not fully independent — possible self-favoring bias.
• **Domain metric limits.** med_coverage catches lost terms but doesn't judge whether a missing term would matter clinically.

These aren't excuses — they're the boundaries of what the n=50 evidence can support. Per-model effects need scale, real noise needs real data, and clinical safety needs human review.

→ Here's how we'd address those.""",

    18: """Four things to turn this from pilot into a stronger study.

• **Scale to n=1000.** Same fixed_repair and self_repair structure with confidence intervals. Lets us make per-model claims with statistical support.
• **Validate repair outputs.** Reject rewrites that answer the question, ask for clarification, or inject facts not in the noisy input. Right now repair is a free-text rewrite — we should constrain it.
• **Human or clinical review.** Pair the automatic metrics with a harm-tier rubric for misleading, unsafe, or clinically dangerous answers. The judge can't catch what would actually hurt a patient.
• **Noise-specific policy.** Apply repair selectively. Typos and incomplete questions probably benefit. Overgeneralized or ambiguous prompts probably need a clarifying question instead of a rewrite.

The bottom line — and this is what we'd want a deployment team to take away:

**Prompt repair should be evaluated as a CONDITIONAL tool, not assumed to be a universal safety layer.**

→ That's the talk.""",

    19: """The main answer in one sentence:

Repair improved question intent in every model, but did NOT systematically improve medical QA answer quality in the completed n=50 pilot.

Happy to take questions — and especially counter-evidence. If anyone has examples of patient-portal data, deployment experience, or domain feedback we should be paying attention to, we'd love to hear it.

Thank you.""",
}


def main() -> None:
    if not SRC.exists():
        raise FileNotFoundError(SRC)

    shutil.copy2(SRC, DST)
    prs = Presentation(DST)

    if len(prs.slides) != len(NOTES):
        raise RuntimeError(
            f"Expected {len(NOTES)} slides, got {len(prs.slides)} — "
            "update NOTES dict to match deck length."
        )

    for idx, slide in enumerate(prs.slides, start=1):
        text = NOTES[idx]
        notes_tf = slide.notes_slide.notes_text_frame
        notes_tf.clear()
        # First paragraph already exists after clear()
        first_line, *rest = text.split("\n")
        p = notes_tf.paragraphs[0]
        run = p.add_run()
        run.text = first_line
        for line in rest:
            p = notes_tf.add_paragraph()
            run = p.add_run()
            run.text = line

    prs.save(DST)
    print(f"Wrote speaker notes for {len(prs.slides)} slides -> {DST}")


if __name__ == "__main__":
    main()
